Resources:
  DemoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "DemoQueue"
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt: [DemoQueueDLQ, Arn]
        maxReceiveCount: 2

  DemoQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "DemoQueueDLQ"